services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - TZ=Europe/Helsinki
      - DB_PATH=/app/data/database.sqlite
    volumes:
      - db_data:/app/data
    restart: unless-stopped

volumes:
  db_data: